create type public.student_program as enum ('kids', 'adult');
create type public.staff_role as enum ('owner', 'admin', 'instructor');

create table public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role public.staff_role not null default 'instructor',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.students (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  program public.student_program not null,
  active boolean not null default true,
  rank text not null default 'White',
  belt_size text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.class_sessions (
  id text primary key,
  program public.student_program not null,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  slot text not null default '',
  label text not null default '',
  start_time time,
  end_time time,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  class_date date not null,
  session_id text references public.class_sessions(id) on delete restrict,
  present boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.promotions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  promotion_date date not null,
  previous_rank text not null default '',
  new_rank text not null,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.waivers (
  id uuid primary key default gen_random_uuid(),
  student_id bigint not null references public.students(id) on delete restrict,
  waiver_version integer not null default 1 check (waiver_version > 0),
  participant_name text not null default '',
  parent_guardian_name text not null default '',
  phone text not null default '',
  email text not null default '',
  emergency_name text not null default '',
  emergency_phone text not null default '',
  signed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.class_notes (
  id bigint generated by default as identity primary key,
  program public.student_program not null,
  class_date date not null,
  title text not null default '',
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (program, class_date)
);

create table public.idea_notes (
  id bigint generated by default as identity primary key,
  title text not null default '',
  content text not null default '',
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_settings (
  id bigint generated by default as identity primary key,
  setting_key text not null unique,
  setting_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create unique index attendance_student_date_session_key
  on public.attendance (student_id, class_date, coalesce(session_id, ''));

create index attendance_student_id_idx on public.attendance (student_id);
create index promotions_student_id_idx on public.promotions (student_id);
create index waivers_student_id_idx on public.waivers (student_id);
create index idea_notes_created_by_idx on public.idea_notes (created_by);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger user_profiles_set_updated_at before update on public.user_profiles for each row execute function public.set_updated_at();
create trigger students_set_updated_at before update on public.students for each row execute function public.set_updated_at();
create trigger class_sessions_set_updated_at before update on public.class_sessions for each row execute function public.set_updated_at();
create trigger attendance_set_updated_at before update on public.attendance for each row execute function public.set_updated_at();
create trigger promotions_set_updated_at before update on public.promotions for each row execute function public.set_updated_at();
create trigger waivers_set_updated_at before update on public.waivers for each row execute function public.set_updated_at();
create trigger class_notes_set_updated_at before update on public.class_notes for each row execute function public.set_updated_at();
create trigger idea_notes_set_updated_at before update on public.idea_notes for each row execute function public.set_updated_at();
create trigger app_settings_set_updated_at before update on public.app_settings for each row execute function public.set_updated_at();

create or replace function public.current_user_role()
returns public.staff_role
language sql
security definer
stable
set search_path = public
as $$
  select role from public.user_profiles
  where user_id = auth.uid() and active = true
  limit 1;
$$;

alter table public.user_profiles enable row level security;
alter table public.students enable row level security;
alter table public.class_sessions enable row level security;
alter table public.attendance enable row level security;
alter table public.promotions enable row level security;
alter table public.waivers enable row level security;
alter table public.class_notes enable row level security;
alter table public.idea_notes enable row level security;
alter table public.app_settings enable row level security;

create policy user_profiles_select_self_or_owner on public.user_profiles
  for select to authenticated
  using (user_id = auth.uid() or public.current_user_role() = 'owner');

create policy user_profiles_insert_owner on public.user_profiles
  for insert to authenticated
  with check (public.current_user_role() = 'owner');

create policy user_profiles_update_owner on public.user_profiles
  for update to authenticated
  using (public.current_user_role() = 'owner')
  with check (public.current_user_role() = 'owner');

create policy user_profiles_delete_owner on public.user_profiles
  for delete to authenticated
  using (public.current_user_role() = 'owner');

create policy students_select_staff on public.students
  for select to authenticated
  using (public.current_user_role() is not null);
create policy students_insert_staff on public.students
  for insert to authenticated
  with check (public.current_user_role() is not null);
create policy students_update_staff on public.students
  for update to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);
create policy students_delete_staff on public.students
  for delete to authenticated
  using (public.current_user_role() is not null);

create policy class_sessions_select_staff on public.class_sessions
  for select to authenticated
  using (public.current_user_role() is not null);
create policy class_sessions_insert_staff on public.class_sessions
  for insert to authenticated
  with check (public.current_user_role() is not null);
create policy class_sessions_update_staff on public.class_sessions
  for update to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);
create policy class_sessions_delete_staff on public.class_sessions
  for delete to authenticated
  using (public.current_user_role() is not null);

create policy attendance_all_staff on public.attendance
  for all to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);

create policy promotions_all_staff on public.promotions
  for all to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);

create policy waivers_all_staff on public.waivers
  for all to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);

create policy class_notes_all_staff on public.class_notes
  for all to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);

create policy idea_notes_all_staff on public.idea_notes
  for all to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);

create policy app_settings_all_staff on public.app_settings
  for all to authenticated
  using (public.current_user_role() is not null)
  with check (public.current_user_role() is not null);
